import os

source = "#pragma once\n\n"
source += "/******\nThis File was autogenerated by \"GenerateShaders.py\"\nEdit the shader code directly, within this current directory.\nTo update the shader code, EITHER:\n\t1) Trigger a rebuild for this file, in order that the post-build step may update this file.\n\t2) Run \"GenerateShaders.bat\" (located within the same directory).\n\tNot working? Python3 is required to be installed and setup for this custom script to execute.\n******/\n\n"
source += "namespace Yeastem {\n\tnamespace Shaders {\n"

def readFile(x):
        with open(x, mode="r") as file:
                l = file.read().split("\n")
                l[0] += "\\n"
                for i in range(len(l)):
                        l[i] = l[i].replace("\"", "\\" + "\"")
                        l[i] = l[i].strip()
                        if "//" in l[i]:
                                l[i] = l[i][l[i].find("//"):]
                                l[i] = l[i].strip()
                l = filter(lambda x: x, l)
                return " ".join(l)

for x in os.listdir():
    if x.endswith(".vert"):
        source += "\t\tinline char " + x.replace(".vert", "_VERT") + "[]=\"" + readFile(x) + "\";\n"
    if x.endswith(".frag"):
        source += "\t\tinline char " + x.replace(".frag", "_FRAG") + "[]=\"" + readFile(x) + "\";\n"

source += "\t}\n}\n"

with open("Shaders.h", mode="w") as shaderFile:
         shaderFile.write(source)
